### ISSUE TITLE
Discord Placeholders

### ISSUE THREAD

**Issue by tigerboy985** [DiscordSRV/Staff-Chat#12]
I have this set: 

> in-game-message-format: "[&bMinecraft Staff Chat &r| %luckperms_primary_group_name%&r] %essentials_nickname%: %message%"
discord-message-format: "[&bDiscord Staff Chat &r| %toprolecolor%%toprole%&r] %username%: %message%"

However in-game it displays: 
![image](https://user-images.githubusercontent.com/43861729/78930449-0d9b7480-7a9c-11ea-8f2d-2f34e06afdd7.png)

**Comment by pkrok01** [comment]
1. Install the PlaceholderAPI plugin https://www.spigotmc.org/resources/placeholderapi.6245/
2. do `/papi ecloud download DiscordSRV`
3. Use the placeholder you want from 
https://github.com/DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion#placeholders
4. `/papi reload` or restart your server

**Comment by RezzedUp** [comment]
Use PAPI just as @pkrok01 said.
