### ISSUE TITLE
Disable or change command aliases

### ISSUE THREAD

**Issue by schotje0013** [DiscordSRV/Staff-Chat#13]
Hello,
I would like to remove the /schat and the /sc commands.
It overlaps with another plugin I use.
How is this possible?

**Comment by RezzedUp** [comment]
There are a few solutions to your overlapping-commands problem with varying degrees of complexity.

---

The simplest solution is using prefixed commands: `<plugin>:<command>` (e.g. `somechat:schat` and `discordsrv-staff-chat:sc`), but I do understand that prefixing commands is cumbersome and indequate.

Another solution, incorporating command prefixing above, involves either modifying the `commands.yml` file at the root of your server directory (which you can [read about here](https://bukkit.gamepedia.com/Commands.yml)) or installing an aliases plugin. Simply create an alias that executes the affected commands (i.e. an `/sc` alias that executes `<plugin>:sc`).

---

The third and final solution involves opening `DiscordSRV-Staff-Chat.jar` with a zip archive tool (like 7zip or winrar) and modifying the `plugin.yml` file included with the plugin. Simply remove the `sc` and `schat` aliases from the file.

Modify line 15 of `plugin.yml` from this:
```yaml
aliases: [adminchat, schat, achat, sc, ac, a]
```
to this:
```yaml
aliases: [adminchat, achat, ac, a]
```

**Comment by schotje0013** [comment]
The last one worked for me! Thanks!
I have another question, but i will open another ticket for that
