### ISSUE TITLE
%name% only displays Discord username, not nick

### ISSUE THREAD

**Issue by DB8888** [DiscordSRV/Staff-Chat#15]
When I do %name% as a placeholder in config.yml, it only displays the Discord username of the user. When I try to use other placeholders like %displayname% and %nickname%, it displays the nickname fine but if the user does not have a nickname, it just displays the placeholder in game, without subbing in a value.

I'm running Staffchat V1.3.0 and DiscordSRV V1.18.4. I do not have PlaceholderAPI installed.

**Comment by GreemDev** [comment]
First of all, try updating DiscordSRV and DiscordSRV-StaffChat. Both are outdated.

**Comment by RezzedUp** [comment]
This was recently fixed in 1.3.2. In the future, please ensure you're using the most up-to-date version before opening an issue.
