### ISSUE TITLE
Option to toggle staff chat

### ISSUE THREAD

**Issue by TheMKDev** [DiscordSRV/Staff-Chat#16]
I have a suggestion to add a command to toggle staff chat from showing up. Maybe somthing like `/togglestaffchat`.

**Comment by RezzedUp** [comment]
Is there a specific use case you have in mind for a feature like this? Personally, I wouldn't want my staff to miss out on important messages in staff chat.

**Comment by TheMKDev** [comment]
It would be useful if a staff is screensharing or streaming and they don't want to show the staffchat.

**Comment by Shrill64** [comment]
Came here to ask the same, perfect! (Having "/togglestaffchat" would compliment other chat plugin commands like "/togglechat" from chatmanager, so people would not have to be "forced" to view the staffchat messages.

**Comment by ZEROOblivious** [comment]
Please add this feature, we use Staff Chat for other things.  
Please make this toggle-able.

**Comment by RezzedUp** [comment]
Added `/leavestaffchat` in 1.4.0.
