### ISSUE TITLE
Add an option for prefixed messages rather than always typing commands

### ISSUE THREAD

**Issue by ablac** [DiscordSRV/Staff-Chat#17]
I’m currently running a BungeeCord and using Spartan for staff chat which is super simple you just put an @(message) no / required and it does the staff chat. Is there a way way to implement this into the staff-chat plugin for discordSCV? Even if you just add the alias @ I can disable Spartans, but I’m also worried will this work across a bungee network for staff chat as well?

**Comment by RezzedUp** [comment]
This is not a bungee plugin, so it won't work across your network unless it's installed on each server (just like DiscordSRV itself).

As for the `@` prefix thing, I suppose I could add a configurable option for it. However, `/a` exists as an alias for `/staffchat` which is short enough in my experience.

**Comment by ablac** [comment]
Or could you search for staff chat from another plugin starting with @, which could be configureable, so users can put in search for x as staffchat and post the message to discord. When receiving from discord use command x to send message. (for example)?

**Comment by RezzedUp** [comment]
> Or could you search for staff chat from another plugin starting with @, which could be configureable, so users can put in search for x as staffchat and post the message to discord. When receiving from discord use command x to send message. (for example)?

I honestly have no idea what you're trying to say here, but if/when I end up adding the config options, I'd also let you choose which prefix to use.

An example of what I mean:

```yaml
enable-prefixed-chat-messages: true
prefixed-chat-identifier: "@"
```

**Comment by ablac** [comment]
:) that works perfect! Sorry for it being confusing, but I was basically trying to say is there a way to make the plugin search for the staff command issued by a user from a third party plugin. So for example when I do @ it runs the message through Spartan so if I say @Test it would send a StaffMessage as Test.

Then the discord plugin would search for that and go ok that’s the StaffCommand (Defined in config) I should be looking for, and issue “Test” to the staff discord. And in reverse it would use that command and issue @(message) to the server.

But! Adding the @ alias is much easier and accomplishes the same results :) with half the amount of work :D thank you!

**Comment by RezzedUp** [comment]
Added as of version1.3.4.
