### ISSUE TITLE
toprolecolor placeholder does not work with Staff-Chat formatting.

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/Staff-Chat#21]
DiscordSRV-Build-1.22.0-SNAPSHOT-1612054948
Staff-Chat v1.3.3

``%toprolecolor%`` placeholder from DiscordSRV does not work in Staff-Chat formatting. The placeholder works fine in DiscordSRV messages sent in-game, just not staff-chat messages sent to Staff-Chat's channel.

**Comment by RezzedUp** [comment]
Added in `1.4.1`

**Comment by mibby** [comment]
Thanks!
