### ISSUE TITLE
Way for discord messages to show up ingame

### ISSUE THREAD

**Issue by BradtheRad** [DiscordSRV/Staff-Chat#22]
I can see in the config there's a thing called: 
discord-message-format: "&9&ldiscord &f-> &d(&5&l&oStaff&d) %name%&7:&f %message%"

This makes me think there is a way to have messages go in game from discord, but it doesn't work. I have my messages from in-game go to discord, so it's all set up correctly, just wondering if I did something wrong / there's a way to have messages show up in-game from discord. Thanks.

**Comment by NooberPlays** [comment]
It is possible

**Comment by RezzedUp** [comment]
It certainly is possible, that's sorta why this plugin exists. 😛 

Please ensure your bot has permission to read messages from your staff chat channel (also make sure it has permission to see the **message history**, that may affect its ability to detect messages).

**Comment by BradtheRad** [comment]
My bot has admin permissions, can view the channel and can view messages. I have it setup so I receive the messages from in game and they go to discord, anything else I could do?

**Comment by slooshied** [comment]
Experiencing the same issue, I believe something has become bunged up with the newer updates of DiscordSRV.

**Comment by RezzedUp** [comment]
Let's get some version information.

It works on my end using DiscordSRV `1.21.3` with DiscordSRV-Staff-Chat `1.3.3` on Paper `1.16.5 build 465`.

![](https://i.imgur.com/QhnHIt9.png)
