### ISSUE TITLE
Ability to talk in staff chat from console

### ISSUE THREAD

**Issue by mifk1** [DiscordSRV/Staff-Chat#26]

**Comment by RezzedUp** [comment]
Is there a reason you'd prefer that over just talking in the staff-chat channel on Discord?

**Comment by mifk1** [comment]
When I'm monitoring console its easier to type in there rather then switching windows

**Comment by HyplexMC** [comment]
Not to mention it provides more customization options, for example i want to set it so i can send a @ to me or my staff when for example a auto ban is issues or a anti-cheat alert comes in so on so forth

**Comment by RezzedUp** [comment]
Added console staff chat message support in 1.4.0.
