### ISSUE TITLE
DiscordSRV Placeholder Support

### ISSUE THREAD

**Issue by AlexTeal03** [DiscordSRV/Staff-Chat#3]
Please could you add placeholders for discord roles as in the DiscordSRV plugin.

**Comment by RezzedUp** [comment]
Added as of 1.3.0.

**Comment by Vankka** [comment]
This isn't neccaserily solved by adding PAPI support as it only solved Minecraft -> Discord (for the most part). Leaving the other side (Discord -> Minecraft) unsolved (role(s) & -colors, etc.).

However reinventing the wheel might not be the best idea, either (eg. copy & pasting placeholders), could do with a little something on DiscordSRV's end

**Comment by RezzedUp** [comment]
As of 1.3.1, both in-game and discord message formats are capable of using PlaceholderAPI placeholders. 

> However reinventing the wheel might not be the best idea, either (eg. copy & pasting placeholders), could do with a little something on DiscordSRV's end

I agree, and if PAPI is still inadequate, then DiscordSRV should expose its placeholder mechanism to other plugins. In the meantime, I consider this issue resolved.
