### ISSUE TITLE
DiscordSRV Staff-Chat is not showing the purple (Staff) prefix when sending messages or enabling the staff chat.

### ISSUE THREAD

**Issue by azolify** [DiscordSRV/Staff-Chat#35]
![image](https://user-images.githubusercontent.com/101532448/158085279-312650ff-3f51-4ea2-9e4c-91f88f955a0b.png)

Here is the image.

**Comment by azolify** [comment]
![image](https://user-images.githubusercontent.com/101532448/158085406-df1ca62b-817b-4aef-826e-d7a67914def2.png)

List of my plugins

**Comment by RezzedUp** [comment]
And what does your `messages.config.yml` look like?

**Comment by azolify** [comment]
https://pastebin.com/stjm6Kau

**Comment by RezzedUp** [comment]
That's your DiscordSRV messages config. I need your **DiscordSRV-Staff-Chat** messages config. (`plugins/DiscordSRV-Staff-Chat/messages.config.yml`)

**Comment by azolify** [comment]
![image](https://user-images.githubusercontent.com/101532448/158105604-f2e43bf7-4929-4762-9920-6868b2bd7831.png)
i don't have a message.config.yml file in my folder

**Comment by RezzedUp** [comment]
Thank you for reporting this bug. It should not be fixed with `1.4.4`.
