### ISSUE TITLE
Message config issue;

### ISSUE THREAD

**Issue by D1sc0rdKitten** [DiscordSRV/Staff-Chat#37]
( This is all referring to in-game, and may or may not affect the discord side of things! )
You are unable to config the messages and prefix with the DiscordSRV-Staff-Chat plugin.
When you go to the messages.config.yml and change how the messages look, it doesn't completely work. You can change how the prefix looks, but that's about it. When you try to change how the messages themselves look, it works and saves but it doesn't change anything. It just looks the same in-game, the plain default given format '%prefix% %name%&7:&f %message%'.
Also, when you do change the prefix. After reloading the plugin it works fine, no issues, but when you restart the server instead of showing the prefix you configured it to, it just shows the placeholder "%prefix%". (I couldn't recreate the issue with just reloading)
![Capture 1](https://user-images.githubusercontent.com/118503879/202631513-7e18f485-42ba-447a-bf84-7d9dceb66a89.PNG)
![Capture 2](https://user-images.githubusercontent.com/118503879/202631523-70495270-ac67-4839-86e1-d322b8a05acc.PNG)

**Comment by RezzedUp** [comment]
I'm unable to reproduce this behavior with DiscordSRV-Staff-Chat v`1.4.4`.
This is my prefix/in-game chat format after restarting the server:
![](https://i.imgur.com/CP3qbQn.png)

Although, what I suspect is happening is that your edited config contains formatting errors resulting in invalid YAML. This would explain why it uses the default prefix when reloading and ultimately no prefix at all when restarting. Please check your console for any YAML-related errors and run any changes you make through a YAML validator (like https://www.yamllint.com/).
