### ISSUE TITLE
Rank is doubled with LuckPerms role name

### ISSUE THREAD

**Issue by Kxsumi** [DiscordSRV/Staff-Chat#40]
![image](https://user-images.githubusercontent.com/96434998/222068369-dacbe47b-1445-473a-b8c5-74b5ada0c702.png)
![image](https://user-images.githubusercontent.com/96434998/222069014-64037928-2b5b-4812-8846-463508ddb223.png)
![image](https://user-images.githubusercontent.com/96434998/222069296-e5f8ad85-e33f-4071-b07d-346192777ec5.png)
Any ideas on how to fix this? Chat formatter is EssentialsChat.

**Comment by GreemDev** [comment]
This is not an appropriate place to post questions with the plugin.
Go to the [DiscordSRV support server](https://discord.discordsrv.com) and go to the support channel.
