### ISSUE TITLE
Sound & Direct Chat Suggestion

### ISSUE THREAD

**Issue by NotGeri** [DiscordSRV/Staff-Chat#9]
Hey there!
I've been using this plugin for quite a while now and I never had an issues with it but it always lacked two features for me. 

Having of things to pay attention to gets quite challenging especially in an unorganised Minecraft chat with no real way to categorize things. A really easy way to make people pay attention to something are sounds. My idea is to have sound support for the plugin. When somebody sends a message in staff chat, every only player with permission to view and use the chat would get notified. 
In my opinion it's a nice thing to add more options for server owners I'd love to have pitch and volume support as well. 
`# You can use sounds from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound: BLOCK_ANVIL_HIT
pitch: 1
volume: 10`

My other suggestion is to have a setting in the config which would allow direct chatting. Currently, in order to chat, players would either have to toggle staff chat or use a command such as `/ac` (`/adminchat`) - In my opinion having a single character is just really nice. 
`direct-chat-prefix: #`
This would mean that any message which has the `#` prefix would be sent to staff chat, of course if they have the permissions to view and send messages there. 

I also have a small 'bug' report. When somebody toggles staff chat and talks that way, messages are not formatted like the ones which are sent with the regular command.

**Comment by RezzedUp** [comment]
Very interesting ideas. I will look into adding them soon.

> I also have a small 'bug' report. When somebody toggles staff chat and talks that way, messages are not formatted like the ones which are sent with the regular command.

Could you elaborate further in a separate issue? It seems unrelated to the suggestions that make up a bulk of the post. I would also appreciate screenshots.

**Comment by NotGeri** [comment]
Yes, it's not related to the suggestion. 
So, when somebody writes in the staff channel using the `/staffchat` command, it follows the format I have setup in config. But when somebody toggles the chat and talks like that, it does not. The colour can be seen here. 

**Config:**
`#
#   DiscordSRV-Staff-Chat v1.3.0 by RezzedUp
#
#   ---
#
#   This plugin *requires* DiscordSRV in order to access Discord.
#   It will, however, work just fine in-game regardless whether DiscordSRV is installed or not.
#   
#   ---
#
#   Installation (Discord Setup):
#
#   - 1) Install this plugin and DiscordSRV
#
#   - 2) Add a "staff-chat" channel to DiscordSRV's config
#
#     EXAMPLE:
#         # Channel links from game to Discord
#         # Replace '00000000000' with your channel's id
#         Channels: {"global": "00000000000", "staff-chat": "00000000000"}
#         #                                        ^              ^
#         #                         All staff chat messages will be sent to this channel.
#
#     IMPORTANT NOTE:
#         The channel's name can be anything on discord (since DiscordSRV uses its channel id) ...
#         However, it MUST be called "staff-chat" in the config.
#         **This is very important!**
#
#   - 3) Restart the server
#
#   - 4) Give staff ranks permission to use the staff chat: 'staffchat.access'
#
#   ---
#
#   This config can be reloaded in-game with: '/managestaffchat reload'
#   (Be sure to give yourself permission to manage the staff chat with: 'staffchat.manage')
#

#
#   *If* PlaceholderAPI is installed, the in-game format will also utilize those.
#   That plugin is not necessary for the existing placeholders in this config, however.
#

in-game-message-format: "&a&lSTAFF &f» &r%name% &7» &a%message%"
discord-message-format: "&a&lSTAFF &f» &r%username% &7» &a%message%"

#
#   Automatic staff-chat toggle messages.
#

enable-staff-chat: "&a&lSTAFF &f» &7You toggle auto staff chat &aon&7."
disable-staff-chat: "&a&lSTAFF &f» &7You toggle auto staff chat &coff&7."

#
#   If a staff member leaves the server with automatic staff chat enabled,
#   this plugin will remember and remind them upon joining back.
#   All toggles will be disabled if this plugin is unloaded (e.g. if the server restarts).
#

notify-staff-chat-enabled-on-join: true
staff-chat-enabled-notification: "&a&lSTAFF &f» &7You have auto staff chat &aon&7."`

**Video:**
https://streamable.com/ba4s9t

**Comment by RezzedUp** [comment]
Added prefixed messages in 1.3.4 and sounds as of 1.4.0.
